language: node_js
node_js:
  - 'node'
cache:
  yarn: true
script: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  fqdn: codingcomrade.com
  on:
    branch: release
